# CI de Nivel 01 - Disparo manual a partir de 1 clique 

# Nome que vai aparecer nas opções de pipi
name: 'Execução Manual - nivel 1'
    #Triggers, ou gatilhos de execução
    #Gatlhos de exec manual = workflow_dispach 

    
on:
    workflow_dispatch:

    
    
jobs:

        # descrição do job
    e2e-tests:
            # Maquina que o job vai executar 
        runs-on: ['ubuntu-latest']

            # passo a passo das ações do job
        steps: 
            - uses: actions/checkout@v4

            - name: Instalando Dependências 
              run: npm install -g yarn

            - name: Instalando depedências 
              run: yarn 

            - name: Instalando Playwright
              run: yarn playwright install

            - name: Teste E2E 
              run: yarn run e2e